from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(693, 220)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(320, 160, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.widget = QtGui.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(30, 32, 641, 100))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.music_player = QtGui.QLineEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.music_player.sizePolicy().hasHeightForWidth())
        self.music_player.setSizePolicy(sizePolicy)
        self.music_player.setMinimumSize(QtCore.QSize(500, 0))
        self.music_player.setObjectName(_fromUtf8("music_player"))
        self.gridLayout.addWidget(self.music_player, 0, 0, 1, 1)
        self.set_music_player = QtGui.QToolButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.set_music_player.sizePolicy().hasHeightForWidth())
        self.set_music_player.setSizePolicy(sizePolicy)
        self.set_music_player.setObjectName(_fromUtf8("set_music_player"))
        self.gridLayout.addWidget(self.set_music_player, 0, 1, 1, 1)
        self.music_dir = QtGui.QLineEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.music_dir.sizePolicy().hasHeightForWidth())
        self.music_dir.setSizePolicy(sizePolicy)
        self.music_dir.setMinimumSize(QtCore.QSize(500, 0))
        self.music_dir.setObjectName(_fromUtf8("music_dir"))
        self.gridLayout.addWidget(self.music_dir, 1, 0, 1, 1)
        self.set_music_dir = QtGui.QToolButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.set_music_dir.sizePolicy().hasHeightForWidth())
        self.set_music_dir.setSizePolicy(sizePolicy)
        self.set_music_dir.setBaseSize(QtCore.QSize(100, 0))
        self.set_music_dir.setObjectName(_fromUtf8("set_music_dir"))
        self.gridLayout.addWidget(self.set_music_dir, 1, 1, 1, 1)
        self.video_player = QtGui.QLineEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video_player.sizePolicy().hasHeightForWidth())
        self.video_player.setSizePolicy(sizePolicy)
        self.video_player.setMinimumSize(QtCore.QSize(500, 0))
        self.video_player.setObjectName(_fromUtf8("video_player"))
        self.gridLayout.addWidget(self.video_player, 2, 0, 1, 1)
        self.set_video_player = QtGui.QToolButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.set_video_player.sizePolicy().hasHeightForWidth())
        self.set_video_player.setSizePolicy(sizePolicy)
        self.set_video_player.setObjectName(_fromUtf8("set_video_player"))
        self.gridLayout.addWidget(self.set_video_player, 2, 1, 1, 1)
        self.video_dir = QtGui.QLineEdit(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video_dir.sizePolicy().hasHeightForWidth())
        self.video_dir.setSizePolicy(sizePolicy)
        self.video_dir.setMinimumSize(QtCore.QSize(500, 0))
        self.video_dir.setObjectName(_fromUtf8("video_dir"))
        self.gridLayout.addWidget(self.video_dir, 3, 0, 1, 1)
        self.set_video_dir = QtGui.QToolButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.set_video_dir.sizePolicy().hasHeightForWidth())
        self.set_video_dir.setSizePolicy(sizePolicy)
        self.set_video_dir.setObjectName(_fromUtf8("set_video_dir"))
        self.gridLayout.addWidget(self.set_video_dir, 3, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.music_player, self.set_music_player)
        Dialog.setTabOrder(self.set_music_player, self.music_dir)
        Dialog.setTabOrder(self.music_dir, self.set_music_dir)
        Dialog.setTabOrder(self.set_music_dir, self.video_player)
        Dialog.setTabOrder(self.video_player, self.set_video_player)
        Dialog.setTabOrder(self.set_video_player, self.video_dir)
        Dialog.setTabOrder(self.video_dir, self.set_video_dir)
        Dialog.setTabOrder(self.set_video_dir, self.buttonBox)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Configurations", None))
        self.set_music_player.setText(_translate("Dialog", "Choose Music Player", None))
        self.set_music_dir.setText(_translate("Dialog", "Choose Music Dir", None))
        self.set_video_player.setText(_translate("Dialog", "Choose Video Player", None))
        self.set_video_dir.setText(_translate("Dialog", "Choose Video Dir", None))